resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

this_is_a_map 'yes'

--[[
                            ########################################
                            ####			LuisDj#7467			####
                            ####	   Creato il 10/1/2020	    ####
                            ########################################

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXXXXXXNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKXWWKxc,'........',;cldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xlcoO0x:.                   ..;lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,..:kOo'                           .,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWXOl'. .;kOo.                                .,oONMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWKd,.   'd0d'             ....',;;::::::;,'...    .:xXWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWKo'    .;kO:          .';clllllllllllllloodddxddl:,...;xXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNx'     .cOx'       .,cdOXXKOxollc:,'..       ..';coxxxo:,:kNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMW0:.     .c0d.     .;oOXWMWNK0OOOOOO0KKK0ko;.          .,cdxxdONMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWO,      .:Od.    'o0NWXOdc;'..      ..';cdOKKkl'           .;oOXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWx.       ,kx.   ,xXWKx:.                    .:xKXkc.           .:xXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWx.       .ok,  'xXW0l.                          .l0N0o'            ,kNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWk'        ;Oc  cKWKl.                              .lKWKo'           .xWMMMMMMMMMMMMMM
MMMMMMMMMMMMMK;        .ok'.lXWk'    ............................  'kWW0c.          ,0MMMMMMMMMMMMMM
MMMMMMMMMMMMNo         .xo.lNNd.    ...    ................  ....   .dNXko,.         lNMMMMMMMMMMMMM
MMMMMMMMMMMM0,         'xccXWx.     ..                      ...      .xXdld:.        'OMMMMMMMMMMMMM
MMMMMMMMMMMM0'         ,dx0W0,      ..      ..................        ,00,;xc.        oWMMMMMMMMMMMM
MMMMMMMMMMMMNl         'kNWWd.      ..      .................         .oXc.;kc.       :XMMMMMMMMMMMM
MMMMMMMMMMMWNO,        .kWMN:       ..      ..................         cXx. ck;       ,KMMMMMMMMMMMM
MMMMMMMMMMMXxkx.       .oNMX:       ..        .........  ....          :XO. .dx'      ,0MMMMMMMMMMMM
MMMMMMMMMMMNo;kd.       ;0MNc       ..      ................           cXx.  ;Ol.     ,KMMMMMMMMMMMM
MMMMMMMMMMMWd.;kd.      .dNWd.      ..      ................          .dXl   .xk'     :XMMMMMMMMMMMM
MMMMMMMMMMMWO' ,xx'      ,OWK;      ..      ....................      ;K0,    c0:    .oWMMMMMMMMMMMM
MMMMMMMMMMMMXc. .ok:      :KWk.     ..                       ...     .kNo.    ;0l.   ,0MMMMMMMMMMMMM
MMMMMMMMMMMMWk'  .:xd'     cXWx.    ...                    ...      .xNO'     ,Od.  .oNMMMMMMMMMMMMM
MMMMMMMMMMMMMNl.   .lxl.    :KWO,    ..................  ..        ,OW0;      ,0d. .:KMMMMMMMMMMMMMM
MMMMMMMMMMMMMW0,     .cdl'   ,OWXo.                              .oXWK:.      ;0o. ,OWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWk'      .:oo:. .l0NKo'                          'o0WW0;.       c0c.'kWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWk'       .'cll:,,lONXkc,.                  .'lkK0k0x,        .xO,,kWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW0;         ..;cccldONWN0xl:,'.........,:lx0KOocldc.         ;0xl0WMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXo.           ..,:cok0XNNNNXK0000000000kd:'.;oo,.         .xX0XMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWO:.               ..',;:::ccc:::;,'..  .:do;.           lNWWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNk;.                               .;odo,.            cKMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNk:.                         .':odo:.            .:kNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMW0o,.                .';cloddl;..           .,o0NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc;,,,,,,;::clodddoc:;..            .;oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNX0kdol:;,'..             .,:okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkdolc:;;;;;,,,;:cldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

]]